version: '3.3'
services:
  app:
    build:
      context: ./
    restart: always
    volumes:
      - ${configfile}:/usr/src/app/configs/config.json
      - ${responsesfile}:/usr/src/app/configs/responses.json
    environment:
      DBhost: db
      DBname: voraphiliac
      DBuser: voraphiliac
      DBpassword:
      token:

  db:
    image: mariadb:latest
    restart: always
    # ports:
    #   - "${DBextPort}:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DBrootPassword}
      MYSQL_DATABASE: voraphiliac
      MYSQL_USER: voraphiliac
      MYSQL_PASSWORD: ${DBpassword}

volumes:
  db_data:
