services:
  app:
    build:
      context: ./
      secrets:
        - configFile
        - responsesFile
    restart: on-failure

secrets:
  configFile:
    file: ${configfile}
  responsesFile:
    file: ${responsesfile}