version: '3.3'
services:
  app:
    build:
      context: ./
    restart: on-failure
    volumes:
      - ${configfile}:/usr/src/voraphiliac/src/configs/config.json
      - ${responsesfile}:/usr/src/voraphiliac/src/configs/responses.json