services:
  app:
    build:
      context: ./
    restart: on-failure
    secrets:
      - configFile
      - responsesFile

secrets:
  configFile:
    file: ${configfile}
  responsesFile:
    file: ${responsesfile}